# Generated by Django 4.2.7 on 2026-01-28 03:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("programs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="lessonprogress",
            name="first_accessed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lessonprogress",
            name="is_overridden",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lessonprogress",
            name="last_accessed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lessonprogress",
            name="overridden_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lessonprogress",
            name="overridden_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="overridden_progress",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="lessonprogress",
            name="override_note",
            field=models.TextField(blank=True, help_text="Reason for override"),
        ),
        migrations.AddField(
            model_name="lessonprogress",
            name="total_time_spent_seconds",
            field=models.IntegerField(
                default=0, help_text="Total time spent in seconds"
            ),
        ),
        migrations.AddField(
            model_name="module",
            name="end_month",
            field=models.IntegerField(default=1, help_text="Ending month (1-12)"),
        ),
        migrations.AddField(
            model_name="module",
            name="program",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="modules",
                to="programs.program",
            ),
        ),
        migrations.AddField(
            model_name="module",
            name="start_month",
            field=models.IntegerField(default=1, help_text="Starting month (1-12)"),
        ),
        migrations.AlterField(
            model_name="module",
            name="month",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="modules",
                to="programs.month",
            ),
        ),
        migrations.CreateModel(
            name="ModuleProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                        ],
                        default="not_started",
                        max_length=20,
                    ),
                ),
                ("progress_percentage", models.IntegerField(default=0)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("is_overridden", models.BooleanField(default=False)),
                ("overridden_at", models.DateTimeField(blank=True, null=True)),
                (
                    "override_note",
                    models.TextField(blank=True, help_text="Reason for override"),
                ),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress",
                        to="programs.module",
                    ),
                ),
                (
                    "overridden_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="overridden_module_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="module_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "module_progress",
                "unique_together": {("user", "module")},
            },
        ),
    ]
