# Generated by Django 4.2.7 on 2026-01-28 03:39

from django.db import migrations


def populate_module_program(apps, schema_editor):
    """Populate module.program from month.program for existing data"""
    Module = apps.get_model('programs', 'Module')
    for module in Module.objects.select_related('month').all():
        if module.month:
            module.program = module.month.program
            # Set start and end month from month.month_number
            module.start_month = module.month.month_number
            module.end_month = module.month.month_number
            module.save()


def reverse_populate(apps, schema_editor):
    """Reverse migration - clear program field"""
    Module = apps.get_model('programs', 'Module')
    Module.objects.all().update(program=None, start_month=1, end_month=1)


class Migration(migrations.Migration):

    dependencies = [
        ("programs", "0002_lessonprogress_first_accessed_at_and_more"),
    ]

    operations = [
        migrations.RunPython(populate_module_program, reverse_populate),
    ]
